### ISSUE TITLE
PerformInteraction parameter min array size is 0

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/rpc_spec#1]
[MOBILE_API.xml](https://github.com/smartdevicelink/sdl_core/blob/46ed776c537131e72747538488b213cf45f23e22/src/components/interfaces/MOBILE_API.xml#L2754-2756) - The PerformInteraction command has an array field `interactionChoiceSetIDList` which has the min array size set to 0.  Other arrays require a minimum length of 1, not 0.

**Comment by mikeburke106** [comment]
Same issue for ScrollableMessage `softButtons` parameter.

**Comment by joeljfischer** [comment]
> Same issue for ScrollableMessage softButtons parameter.

Should be a separate issue, so that it can be tracked, searched, and fixed separately, or a more general issue title should be created.

**Comment by jacobkeeler** [comment]
Outdated
