### ISSUE TITLE
Spelling issue in `RegisterAppInterface` response `hmiCapabilities` description

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/rpc_spec#177]
The `RegisterAppInterface` response `hmiCapabilities` description contains a spelling issue: 
> Specifies the HMIÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s capabilities. See HMICapabilities.

It should probably be:
> Specifies the HMI capabilities. See HMICapabilities.

**Comment by theresalech** [comment]
Closed via #194
