### ISSUE TITLE
[SDL 0234] Proxy Library RPC Generation

### ISSUE THREAD

**Issue by vladmu** [smartdevicelink/rpc_spec#203]
Proposal: [Proxy Library RPC Generation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0234-proxy-rpc-generation.md)

> This proposal adds automatic RPC generation for iOS and Java from the XML spec via a python script.

Review: [smartdevicelink/sdl_evolution#741](https://github.com/smartdevicelink/sdl_evolution/issues/741)

Steering Committee Decision:

> The Steering Committee voted to approve this proposal with the following revision: there will be parsing code in each repository, and the rpc spec will be a submodule that pins which rpc spec will be used in each version of the library.

> The proposal .md file was updated to reflect these revisions on 6/10/19.

**Comment by vladmu** [comment]
PR #202 created as prerequisites following this issue and proposal. The further specification of each generator script requires this schema definition.
Related issues:

- Java: https://github.com/smartdevicelink/sdl_java_suite/issues/1090
- iOS: https://github.com/smartdevicelink/sdl_ios/issues/1298
- JavaScript: https://github.com/smartdevicelink/sdl_javascript_suite/issues/2

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0234 Revisions - Proxy Library RPC Generation](https://github.com/smartdevicelink/sdl_evolution/issues/853). Please reference issue and proposal markdown file for more details.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0234 Revisions - Proxy Library RPC Generation](https://github.com/smartdevicelink/sdl_evolution/issues/990). The revisions include adding a rule that takes into account a set of keywords that currently exist in any of the three client side libraries (iOS, Java Suite, and JavaScript suite), and avoiding creating method signatures that collide.  Please reference the issue and proposal markdown file for more details.

Separate issue has been entered in RPC Spec to reflect this change: https://github.com/smartdevicelink/rpc_spec/issues/231.
