### ISSUE TITLE
Incorrect since value for AppInfo

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/rpc_spec#206]
The `since` value for `appInfo` in `RegisterAppInterface` states it was introduced in version 2.0. However the struct it uses as its type wasn't introduced until 4.2. 

See [here](https://github.com/smartdevicelink/rpc_spec/blob/c87eb000ed8860da48f840838ef4dc5da09a7541/MOBILE_API.xml#L4538)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/rpc_spec/pull/311
