### ISSUE TITLE
WeatherData.currentTemperature should be a stand-in for future anticipated temperatures as well

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/rpc_spec#208]
When dealing with `WeatherServiceData`, we have to use the `WeatherData` struct to construct both the current as well as future hourly and daily temperatures. Some weather APIs may not provide data for, for example, future hourly or minutely highs and lows. In that case the "anticipated" temperature for a future hour should be stored in `WeatherServiceData.hourlyForecast.currentTemperature`. 

We should add a description to the `WeatherData.currentTemperature` parameter stating something like "This parameter contains the current temperature or the anticipated future temperature if only one temperature is available."

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/rpc_spec/pull/289
