### ISSUE TITLE
The value range of PerformAudioPassThru.maxDuration is unreasonable

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/rpc_spec#210]
In https://www.smartdevicelink.com/zh-hans/guides/hmi/ui/performaudiopassthru/,
The value range of PerformAudioPassThru.maxDuration is defined as 1～1000000.

In practical use, if the PerformAudioPassThru.maxDuration is set too small, for instance, 1ms,
then it is obviously not enough for the HU to handle APT.
So, I'm inclined to think that the range should be defined as 3000～1000000 is more reasonable,
since 3000ms is long enough for the HU.

For example, in https://www.smartdevicelink.com/zh-hans/guides/hmi/ui/alert/,
It is reasonable that Alert.duration is defined as 3000～10000.

**Comment by theresalech** [comment]
I'm closing this issue as the requested change will require an accepted SDL Evolution Proposal.  Please submit a proposal in the sdl_evolution repository, following this [template](https://github.com/smartdevicelink/sdl_evolution/blob/master/0000-template.md).  Once the Steering Committee has reviewed and accepted the proposal, I'll enter issues in affected repositories for implementation.  Thanks!
