### ISSUE TITLE
[SDL 0240] WebEngine support for SDL JavaScript

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/rpc_spec#214]
Proposal: [WebEngine support for SDL JavaScript](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0240-sdl-js-pwa.md)

> This proposal is adding a new transport to the SDL JavaScript library to support (progressive) web apps to run on a WebEngine or a browser.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/767

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- When formatting `locales` in the `manifest.json` file, use standard [(RFC 5646)](https://tools.ietf.org/html/rfc5646), and convert locale strings when necessary.
- Do not specify the location of the manifest's <script> tag placement within the proposal.
- All revisions included in this PR: https://github.com/smartdevicelink/sdl_evolution/pull/888/files
> The proposal .md file was updated to reflect these revisions on 12/19/19.

**Comment by AByzhynar** [comment]
@theresalech Do we really need this issue here? 
Maybe I missed something but there were no Mobile API changes specified in the proposal. 
Thank you.

**Comment by theresalech** [comment]
Closing as not needed for this implementation.
