### ISSUE TITLE
Incorrect description for "videoStreamingCapability" and "remoteControlCapability"

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/rpc_spec#228]
In the [SystemCapability](https://github.com/smartdevicelink/rpc_spec#systemcapability) table, `videoStreamingCapability` and `remoteControlCapability` have incorrect descriptions. They have the same description as the `phoneCapability`.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/rpc_spec/pull/238
