### ISSUE TITLE
Enum description should include more details about how integer values are used

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/rpc_spec#234]
There are three enums that currently use `value` as an `integer`: `LightName`, `messageType`, and `PredefinedWindow` however there is no clear description about how and where the integer `value` is used and whether Core should expect integer or string value from proxies:

`messageType` is only used in the protocol binary header as an integer
`PredefinedWindow`  is used as an integer value. Its string value is never used
`LightName` is used as a string value

These enums should include more description to avoid confusion

**Comment by jacobkeeler** [comment]
Closing with the merge of #236
