### ISSUE TITLE
RPC Parser - Parsing default value from a function parameter is broken

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/rpc_spec#285]
## Bug Report
In the RPC InterfaceParser, parsing default value from a function parameter in _rpc_base.py_ is broken because the value at `params["default_value"]` always gets overwritten with `None`. The root of the issue seems to be that the `_parse_function_param()` function tries to parse the default value from the `attrib` dictionary, however the `attrib` dictionary is always empty because `_parse_param_base_item()` does not add any items to the `attrib` dictionary.

**Comment by jacobkeeler** [comment]
Closing with the merge of #286
