### ISSUE TITLE
[SDL 0138] Make 'audioPassThruCapabilities' of HMI an array

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/rpc_spec#63]
Proposal: [Make 'audioPassThruCapabilities' of HMI an array](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0138-hmi-audiopassthru-capability.md)

> The aim of this proposal is to clarify the details of audio data format of AudioPassThru recording.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/393

Steering Committee Decision:

> The Steering Committee has fully agreed to accept this proposal.  It was noted that issues will be added to the project pages for the next major version releases of Core and the RPC Spec to ensure we remove `audioPassThruCapabilities` and make `audioPassThruCapabilitiesList` the only parameter.

**Comment by shoamano83** [comment]
Hi @theresalech ,

I don't think we need to work on this repo since the proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0138-hmi-audiopassthru-capability.md does not update MOBILE_API.xml. (I put the tag "RPC" in the proposal since it updated HMI_API.xml.)

Thanks!

**Comment by theresalech** [comment]
Hi @shoamano83 - agreed.  We will close this issue as it is not required for implementation of SDL 0138.  Thanks!
