### ISSUE TITLE
Many array parameter minimum sizes are 0

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/rpc_spec#7]
**DisplayCapabilities**
- `<param name="mediaClockFormats" type="MediaClockFormat" minsize="0" maxsize="100" array="true">` 
- `<param name="templatesAvailable" type="String" minsize="0" maxsize="100" maxlength="100" array="true" mandatory="false">`

**ParameterPermissions**
- `<param name="allowed" type="String" minsize="0" maxsize="100" maxlength = "100" array="true">`
- `<param name="userDisallowed" type="String" minsize="0" maxsize="100" maxlength = "100" array="true">`

**Alert**
- `<param name="softButtons" type="SoftButton" minsize="0" maxsize="4" array="true" mandatory="false">`

If a minimum size is zero, it should be optional and have a minimum of 1. Otherwise, if the parameter is required the minimum should be 1.

**Comment by jacobkeeler** [comment]
Outdated, any change of this type would be a breaking change and would need a proposal
